# this file is used by github marketplace
# it has to be named exactly `action.yml`
name: "rewiser-gpt"
description: "send rewiser email"
inputs:
  to_email:
    description: "The email Id to sent to"
    required: true
  from_email:
    description: "The email Id to send from"
    required: true 
  doc_directory:
    description: "The directory to read files from"
    required: true
  smtp_hostname:
    description: "SMTP Hostname/endpoint"
    required: true
  smtp_port:
    description: "SMTP server port"
    required: true
  smtp_username:
    description: "SMTP server username, used for logging in"
    required: true
  smtp_password:
    description: "SMTP server password, used for logging in"
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.to_email }}
    - ${{ inputs.from_email }}
    - ${{ inputs.doc_directory }}
    - ${{ inputs.smtp_hostname }}
    - ${{ inputs.smtp_port }}
    - ${{ inputs.smtp_username }}
    - ${{ inputs.smtp_password }}
    
    
