# this file is used by github marketplace
# it has to be named exactly `action.yml`

name: "rewiser-gpt"
description: "send dev logs via email" # TODO: update the description later
inputs:
  name:
    description: "test for checking action" # TODO: fill with actual key value pair
    required: true
outputs: 
  message:
    description: "output message" # TODO: update with correct output 

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.name }}
    
    
