# this file is used by github marketplace
# it has to be named exactly `action.yml`
name: "rewiser-gpt"
description: "send rewiser email"
inputs:
  to_email:
    description: "The email Id to sent to"
    required: true
  from_email:
    description: "The email Id to send from"
    required: true 
  doc_directory:
    description: "The directory to read files from"
    required: true
  smtp_hostname:
    description: "SMTP Hostname/endpoint"
    required: true
  smtp_port:
    description: "SMTP server port"
    required: true
  smtp_username:
    description: "SMTP server username, used for logging in"
    required: true
  smtp_password:
    description: "SMTP server password, used for logging in"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Rewiser mail
      run: |
        echo "installing python dependencies"
        pip install -r requirements.txt
        python main.py
      shell: bash
    
    
