name: Send Devlogs Rewiser Email
on:
  schedule:
    - cron: '30 01 * * *'
  workflow_dispatch:
jobs:
  send_email:
    name: send email
    runs-on: ubuntu-latest
    env:
      DOC_DIRECTORY: "tests"
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - run: git --no-pager log -1 --format=%ad files/anki.py
      # - name: Send rewiser email
      #   uses: mohit2152sharma/rewiser-gpt@main
      #   with:
      #     to_email: ${{ secrets.TO_EMAIL }}
      #     from_email: ${{ secrets.FROM_EMAIL }}
      #     doc_directory: ${{ env.DOC_DIRECTORY }}
      #     smtp_hostname: ${{ secrets.SMTP_HOSTNAME }}
      #     smtp_port: ${{ secrets.SMTP_PORT }}
      #     smtp_username: ${{ secrets.SMTP_USERNAME }}
      #     smtp_password: ${{ secrets.SMTP_PASSWORD }}
