name: Send Devlogs Rewiser Email
on:
  schedule:
    - cron: '30 01 * * *'
  workflow_dispatch:
jobs:
  send_email:
    name: send email
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: mohit2152sharma/rewiser-gpt@main
        with:
          name: "Mohit"
